# bundle.py
import os
import re

def resolve_require(file_path, require_expr):
    # Expressions look like: script.core.window, script.Parent.theme, etc.
    parts = require_expr.strip().split('.')
    if parts[0] != 'script':
        return None
    
    # Get current file directory relative to src
    rel_dir = os.path.dirname(os.path.relpath(file_path, 'src'))
    path_parts = rel_dir.split(os.sep) if rel_dir else []
    
    for part in parts[1:]:
        if part == 'Parent':
            if path_parts:
                path_parts.pop()
        else:
            path_parts.append(part)
            
    return '/'.join(path_parts)

def bundle_project():
    src_dir = 'src'
    modules = {}
    
    # Traverse src directory
    for root, dirs, files in os.walk(src_dir):
        for file in files:
            if file.endswith('.lua'):
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, src_dir)
                module_name = os.path.splitext(rel_path)[0].replace(os.sep, '/')
                
                with open(full_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                    
                # Replace require statements
                # Format: require(script.some.thing) or require(script.Parent.Parent.core.thing)
                pattern = r'require\s*\((script[\w\.\s]*)\)'
                
                def replace_req(match):
                    expr = match.group(1).replace(' ', '')
                    resolved = resolve_require(full_path, expr)
                    if resolved:
                        return f'custom_require("{resolved}")'
                    return match.group(0)
                
                processed_content = re.sub(pattern, replace_req, content)
                modules[module_name] = processed_content

    # Generate bundle content
    bundle_code = """-- QwenUILib Bundled Single-File Library
-- Generated by Antigravity Python Bundler

local modules = {}
local cache = {}

local function custom_require(name)
    if cache[name] then
        return cache[name]
    end
    local func = modules[name]
    if not func then
        error("Module not found: " .. tostring(name))
    end
    local result = func()
    cache[name] = result
    return result
end
"""

    for name, content in modules.items():
        if name != 'init':
            bundle_code += f'\nmodules["{name}"] = function()\n{content}\nend\n'
            
    # Add init module and return it
    bundle_code += f'\n-- Init Module\n{modules["init"]}\n'
    
    os.makedirs('build', exist_ok=True)
    with open('build/bundle.lua', 'w', encoding='utf-8') as f:
        f.write(bundle_code)
    print("Bundle created successfully at build/bundle.lua")

if __name__ == '__main__':
    bundle_project()
